name: SimpleCrossChatPlus
version: '0.2.0'
main: de.liebki.simplecrosschatplus.SimpleCrossChat
api-version: '1.13'
load: STARTUP
softdepend: [Vault]

commands:
  scc:
    description: SimpleCrossChatPlus main command
    usage: /<command> [subcommand] [args]
    aliases: [simplecrosschat, crosschat]
  sccpm:
    description: Send cross-server private message
    usage: /<command> <player> <message>
    aliases: [xpm, crosspm]

permissions:
  sccplus.admin.*:
    description: All SimpleCrossChatPlus admin permissions
    default: op
    children:
      sccplus.admin.disable: true
      sccplus.admin.com: true
      sccplus.admin.info: true
      sccplus.admin.bypass: true

  sccplus.entity.transfer:
    description: Transfer entities cross-server
    default: true

  sccplus.entity.tier.owned:
    description: Transfer owned entities only
    default: true

  sccplus.entity.tier.animals:
    description: Transfer all animals
    default: op

  sccplus.entity.tier.everything:
    description: Transfer any entity type
    default: op

  sccplus.entity.transfer.bypass:
    description: Transfer any entity without tier restrictions
    default: op

  sccplus.item.transfer:
    description: Transfer items cross-server
    default: true

  sccplus.money.transfer:
    description: Transfer money cross-server
    default: true

  sccplus.message.group:
    description: Use group channels
    default: true

  sccplus.player.locate:
    description: Locate players across servers
    default: true

  sccplus.toggle.disabled:
    description: Toggle chat disabled status
    default: true

  sccplus.toggle.notify:
    description: Toggle notification preferences
    default: true
